<?php

declare(strict_types=1);

return new Frosh\Rector\Rule\BCChange\BCChangeConfiguration(
    changes: [
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Cart\CartBehavior',
            method: '__construct',
            position: 2,
            parameter: 'isRecalculation',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Cart\CartException',
            method: 'invalidPriceFieldTypeException',
            currentType: 'Shopware\Core\Checkout\Cart\CartException|Shopware\Core\Framework\DataAbstractionLayer\Exception\InvalidPriceFieldTypeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Cart\CartException',
            method: 'unsupportedOperator',
            currentType: 'Shopware\Core\Checkout\Cart\CartException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterName(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Cart\Order\Transformer\CartTransformer',
            method: 'transform',
            position: 3,
            parameter: 'setOrderDate',
            newName: 'setPersistentData',
            parametersBefore: [
                [
                    'name' => 'cart',
                    'hasDefault' => false,
                ],
                [
                    'name' => 'context',
                    'hasDefault' => false,
                ],
                [
                    'name' => 'stateId',
                    'hasDefault' => false,
                ],
            ],
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Cart\SalesChannel\AbstractCartLoadRoute',
            method: 'load',
            position: 2,
            parameter: 'cart',
            type: '?Shopware\Core\Checkout\Cart\Cart',
            default: null,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerEntity',
            method: 'setActiveBillingAddress',
            parameter: 'activeBillingAddress',
            currentType: 'Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
            type: '?Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerEntity',
            method: 'setActiveShippingAddress',
            parameter: 'activeShippingAddress',
            currentType: 'Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
            type: '?Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerException',
            method: 'invalidOption',
            currentType: 'Shopware\Core\Checkout\Customer\CustomerException|InvalidArgumentException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerException',
            method: 'missingOption',
            currentType: 'Shopware\Core\Checkout\Customer\CustomerException|Symfony\Component\Validator\Exception\MissingOptionsException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerException',
            method: 'productNotFound',
            currentType: 'Shopware\Core\Checkout\Customer\CustomerException|Shopware\Core\Content\Product\Exception\ProductNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerException',
            method: 'unexpectedType',
            currentType: 'Shopware\Core\Checkout\Customer\CustomerException|Symfony\Component\Validator\Exception\UnexpectedTypeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerException',
            method: 'unsupportedOperator',
            currentType: 'Shopware\Core\Checkout\Customer\CustomerException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\CustomerException',
            method: 'unsupportedValue',
            currentType: 'Shopware\Core\Checkout\Customer\CustomerException|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterName(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\SalesChannel\ImitateCustomerRoute',
            method: 'imitateCustomerLogin',
            position: 0,
            parameter: 'requestDataBag',
            newName: 'data',
            parametersBefore: [],
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerEmailUnique',
            method: '__construct',
            position: 0,
            parameter: 'options',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerPasswordMatches',
            method: '__construct',
            position: 0,
            parameter: 'options',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerVatIdentification',
            method: '__construct',
            position: 0,
            parameter: 'options',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerZipCode',
            method: '__construct',
            position: 0,
            parameter: 'options',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Document\DocumentEntity',
            method: 'setOrderId',
            parameter: 'orderId',
            currentType: 'string',
            type: '?string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Document\DocumentEntity',
            method: 'setOrderVersionId',
            parameter: 'orderVersionId',
            currentType: 'string',
            type: '?string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddRequiredParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Document\Zugferd\ZugferdDocument',
            method: 'getContent',
            position: 1,
            parameter: 'calculator',
            type: 'Shopware\Core\Checkout\Cart\Price\AmountCalculator',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Order\OrderException',
            method: 'associationNotFound',
            currentType: 'Shopware\Core\Checkout\Order\OrderException|Shopware\Core\Framework\DataAbstractionLayer\Exception\AssociationNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Payment\Cart\Error\PaymentMethodBlockedError',
            method: 'getPaymentMethodId',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Payment\Cart\Error\PaymentMethodBlockedError',
            method: 'getReason',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Promotion\PromotionException',
            method: 'discountCalculatorNotFound',
            currentType: 'Shopware\Core\Checkout\Promotion\PromotionException|Shopware\Core\Checkout\Promotion\Exception\DiscountCalculatorNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Promotion\PromotionException',
            method: 'invalidScopeDefinition',
            currentType: 'Shopware\Core\Checkout\Promotion\PromotionException|Shopware\Core\Checkout\Promotion\Exception\InvalidScopeDefinitionException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Shipping\Cart\Error\ShippingMethodBlockedError',
            method: 'getReason',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Checkout\Shipping\Cart\Error\ShippingMethodBlockedError',
            method: 'getShippingMethodId',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Category\CategoryException',
            method: 'pageNotFound',
            currentType: 'Shopware\Core\Framework\ShopwareHttpException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Cms\Events\CmsPageLoadedEvent',
            method: 'getResult',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\EntityCollection',
            type: 'Shopware\Core\Content\Cms\CmsPageCollection',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Flow\FlowException',
            method: 'customTriggerByNameNotFound',
            currentType: 'Shopware\Core\Content\Flow\FlowException|Shopware\Core\Content\Flow\Exception\CustomTriggerByNameNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailEntity',
            method: 'getMediaThumbnailSizeId',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailEntity',
            method: 'setUrl',
            parameter: 'url',
            currentType: 'string',
            type: '?string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Media\Thumbnail\ThumbnailService',
            method: 'updateThumbnails',
            position: 3,
            parameter: 'force',
            type: 'bool',
            default: false,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\ProductExport\Struct\ProductExportResult',
            method: '__construct',
            position: 2,
            parameter: 'total',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Product\ProductException',
            method: 'missingRequestParameter',
            currentType: 'Shopware\Core\Content\Product\ProductException|Shopware\Core\Framework\Routing\RoutingException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Product\ProductException',
            method: 'reviewNotActive',
            currentType: 'Shopware\Core\Content\Product\ProductException|Shopware\Core\Content\Product\Exception\ReviewNotActiveExeption',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Product\SalesChannel\Review\Event\ReviewFormEvent',
            method: 'getProduct',
            currentType: '?Shopware\Core\Content\Product\ProductEntity',
            type: 'Shopware\Core\Content\Product\ProductEntity',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Product\SalesChannel\Sorting\ProductSortingEntity',
            method: 'createDalSorting',
            position: 0,
            parameter: 'fallbackSorting',
            type: '?Shopware\Core\Framework\DataAbstractionLayer\Search\Sorting\FieldSorting',
            default: null,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddRequiredParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Content\Property\PropertyGroupCollection',
            method: 'sortByConfig',
            position: 0,
            parameter: 'localeCode',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Adapter\AdapterException',
            method: 'unsupportedOperator',
            currentType: 'Shopware\Core\Framework\Adapter\AdapterException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Adapter\Twig\Extension\NodeExtension',
            method: '__construct',
            parameter: 'finder',
            currentType: 'Shopware\Core\Framework\Adapter\Twig\TemplateFinder',
            type: 'Shopware\Core\Framework\Adapter\Twig\TemplateFinderInterface',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Api\ApiException',
            method: 'apiDefinitionGeneratorNotFound',
            currentType: 'Shopware\Core\Framework\Api\ApiException|Shopware\Core\Framework\Api\ApiDefinition\ApiDefinitionGeneratorNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Context',
            method: 'scope',
            position: 2,
            parameter: 'states',
            type: 'array',
            default: [],
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'cannotBuildAccessor',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'configNotFound',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|Shopware\Elasticsearch\Product\ElasticsearchProductException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'invalidSyncOperationException',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|Shopware\Core\Framework\Api\Exception\InvalidSyncOperationException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'missingTranslatedStorageAwareProperty',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'missingVersionField',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'noTranslationDefinition',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'onlyStorageAwareFieldsAsTranslated',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'onlyStorageAwareFieldsInReadCondition',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'primaryKeyNotStorageAware',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'unexpectedFieldType',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
            method: 'unmappedField',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|Shopware\Core\Framework\DataAbstractionLayer\Dbal\Exception\UnmappedFieldException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterName(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityWriteGateway',
            method: 'prefetchExistences',
            position: 0,
            parameter: 'parameters',
            newName: 'parameterBag',
            parametersBefore: [],
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Event\EntityWrittenContainerEvent',
            method: 'getEvents',
            currentType: '?Shopware\Core\Framework\Event\NestedEventCollection',
            type: 'Shopware\Core\Framework\Event\NestedEventCollection',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterDefault(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Field\CreatedByField',
            method: '__construct',
            position: 0,
            parameter: 'allowedWriteScopes',
            default: [
                'system',
            ],
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            method: 'addFlags',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            type: 'static',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            method: 'removeFlag',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            type: 'static',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            method: 'setDescription',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            type: 'static',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            method: 'setFlags',
            currentType: 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
            type: 'static',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Field\LockedField',
            method: '__construct',
            position: 0,
            parameter: 'lockTranslation',
            type: 'bool',
            default: true,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterDefault(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Field\UpdatedByField',
            method: '__construct',
            position: 0,
            parameter: 'allowedWriteScopes',
            default: [
                'system',
            ],
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Search\Term\Tokenizer',
            method: 'tokenize',
            position: 1,
            parameter: 'tokenMinimumLength',
            type: '?int',
            default: null,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Search\Term\TokenizerInterface',
            method: 'tokenize',
            position: 1,
            parameter: 'tokenMinimumLength',
            type: '?int',
            default: null,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Validation\EntityExists',
            method: '__construct',
            position: 0,
            parameter: 'options',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\DataAbstractionLayer\Validation\EntityNotExists',
            method: '__construct',
            position: 0,
            parameter: 'options',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Event\NestedEventCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\FrameworkException',
            method: 'associationNotFound',
            currentType: 'Shopware\Core\Framework\FrameworkException|Shopware\Core\Framework\DataAbstractionLayer\Exception\AssociationNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\FrameworkException',
            method: 'createFromError',
            currentType: 'Shopware\Core\Framework\FrameworkException|InvalidArgumentException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Plugin\PluginException',
            method: 'kernelPluginLoaderError',
            currentType: 'Shopware\Core\Framework\Plugin\PluginException|Shopware\Core\Framework\Plugin\Exception\KernelPluginLoaderException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Plugin\PluginException',
            method: 'pluginComposerRemove',
            currentType: 'Shopware\Core\Framework\Plugin\PluginException|Shopware\Core\Framework\Plugin\Exception\PluginComposerRemoveException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Plugin\PluginException',
            method: 'pluginComposerRequire',
            currentType: 'Shopware\Core\Framework\Plugin\PluginException|Shopware\Core\Framework\Plugin\Exception\PluginComposerRequireException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Routing\RoutingException',
            method: 'missingMainRequest',
            currentType: 'Shopware\Core\Framework\Routing\RoutingException|InvalidArgumentException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Rule\RuleComparison',
            method: 'date',
            parameter: 'ruleValue',
            currentType: 'DateTime',
            type: '\DateTime|string|array',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Rule\RuleComparison',
            method: 'datetime',
            parameter: 'ruleValue',
            currentType: 'DateTime',
            type: '\DateTime|string|array',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Rule\RuleException',
            method: 'ruleNameNotImplemented',
            currentType: 'Error|Shopware\Core\Framework\Rule\RuleException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Rule\RuleException',
            method: 'unsupportedOperator',
            currentType: 'Shopware\Core\Framework\Rule\RuleException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Rule\RuleException',
            method: 'unsupportedValue',
            currentType: 'Shopware\Core\Framework\Rule\RuleException|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\StoreException',
            method: 'invalidContextSourceUser',
            currentType: 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Api\Context\Exception\InvalidContextSourceUserException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\StoreException',
            method: 'invalidCredentials',
            currentType: 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Store\Exception\StoreInvalidCredentialsException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\StoreException',
            method: 'jwksNotFound',
            currentType: 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\App\AppException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\StoreException',
            method: 'pluginNotAZipFile',
            currentType: 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Plugin\Exception\PluginNotAZipFileException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\StoreException',
            method: 'shopSecretInvalid',
            currentType: 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Store\Exception\ShopSecretInvalidException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\BinaryCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeParameterName(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\DomainVerificationRequestStruct',
            method: '__construct',
            position: 1,
            parameter: 'filename',
            newName: 'fileName',
            parametersBefore: [
                [
                    'name' => 'content',
                    'hasDefault' => false,
                ],
            ],
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\FaqCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\ImageCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\PermissionCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\ReviewCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\StoreCategoryCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\StoreCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Store\Struct\VariantCollection',
            method: 'getExpectedClass',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Util\UtilException',
            method: 'operatorNotSupported',
            currentType: 'Shopware\Core\Framework\Util\UtilException|Shopware\Core\Framework\Util\Exception\ComparatorException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Validation\ValidatorFactory',
            method: 'create',
            position: 2,
            parameter: 'allowExtraFields',
            type: 'bool',
            default: false,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\RemoveParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Webhook\Service\WebhookDeliveryService',
            method: 'process',
            position: 1,
            parameter: 'forceSynchronous',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Webhook\WebhookException',
            method: 'invalidDataMapping',
            currentType: 'Shopware\Core\Framework\Webhook\WebhookException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\Framework\Webhook\WebhookException',
            method: 'unknownEventDataType',
            currentType: 'Shopware\Core\Framework\Webhook\WebhookException|RuntimeException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\Language\LanguageException',
            method: 'unsupportedValue',
            currentType: 'Shopware\Core\System\Language\LanguageException|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\NumberRange\NumberRangeException',
            method: 'incrementStorageNotFound',
            currentType: 'Shopware\Core\System\NumberRange\NumberRangeException|Shopware\Core\System\NumberRange\Exception\IncrementStorageNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\SalesChannel\SalesChannelException',
            method: 'missingAssociation',
            currentType: 'Shopware\Core\System\SalesChannel\SalesChannelException|Shopware\Core\Checkout\Order\OrderException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\SalesChannel\SalesChannelException',
            method: 'orderNotFound',
            currentType: 'Shopware\Core\System\SalesChannel\SalesChannelException|Shopware\Core\Checkout\Order\OrderException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddRequiredParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\Snippet\SnippetFixer',
            method: 'fix',
            position: 1,
            parameter: 'invalidPluralization',
            type: 'Shopware\Core\System\Snippet\Struct\InvalidPluralizationCollection',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\SystemConfig\SystemConfigService',
            method: 'delete',
            position: 2,
            parameter: 'silent',
            type: 'bool',
            default: true,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\SystemConfig\SystemConfigService',
            method: 'set',
            position: 3,
            parameter: 'silent',
            type: 'bool',
            default: true,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Core\System\SystemConfig\SystemConfigService',
            method: 'setMultiple',
            position: 2,
            parameter: 'silent',
            type: 'bool',
            default: true,
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Elasticsearch\ElasticsearchException',
            method: 'operatorNotAllowed',
            currentType: 'Shopware\Elasticsearch\ElasticsearchException|InvalidArgumentException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
            method: 'getNewPaymentMethodId',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
            method: 'getOldPaymentMethodId',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
            method: 'getReason',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
            method: 'getNewShippingMethodId',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
            method: 'getOldShippingMethodId',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
            method: 'getReason',
            currentType: '?string',
            type: 'string',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Controller\Exception\StorefrontException',
            method: 'domainNotFound',
            currentType: 'Shopware\Storefront\Controller\Exception\StorefrontException|Shopware\Core\Content\Newsletter\Exception\SalesChannelDomainNotFoundException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Framework\StorefrontFrameworkException',
            method: 'mediaValidatorMissing',
            currentType: 'Shopware\Storefront\Framework\StorefrontFrameworkException|Shopware\Storefront\Framework\Media\Exception\MediaValidatorMissingException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Theme\Exception\ThemeException',
            method: 'invalidThemeBundle',
            currentType: 'Shopware\Storefront\Theme\Exception\ThemeException|Shopware\Storefront\Theme\Exception\InvalidThemeBundleException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\ChangeReturnType(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Theme\Exception\ThemeException',
            method: 'themeAssignmentException',
            currentType: 'Shopware\Storefront\Theme\Exception\ThemeException|Shopware\Storefront\Theme\Exception\ThemeAssignmentException',
            type: 'self',
        ),
        new Frosh\Rector\Rule\BCChange\ValueObject\AddOptionalParameter(
            version: 'v6.8.0',
            class: 'Shopware\Storefront\Theme\ThemeLifecycleService',
            method: 'refreshTheme',
            position: 2,
            parameter: 'configurationCollection',
            type: '?Shopware\Storefront\Theme\StorefrontPluginConfiguration\StorefrontPluginConfigurationCollection',
            default: null,
        ),
    ],
);
